# Generated by Django 5.1.7 on 2026-07-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_trainingdataset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smsanalysis',
            new_name='analysis_sm_user_id_265244_idx',
            old_name='analysis_s_user_id_2d2b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='smsanalysis',
            new_name='analysis_sm_predict_2a779f_idx',
            old_name='analysis_s_predic_1b4ed0_idx',
        ),
    ]
